

export const departmentsData = [
  {
    id: '1',
    departmentName: 'Engineering',
    headOfDepartment: {
      name: 'Pooja Sarm',
      email: 'pooja.sarm@company.com',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pooja',
    },
    phone: '(123)456-7890',
    email: 'pooja.sarm@company.com',
    employeeCapacity: 125,
    establishedYear: 2015,
    totalEmployees: 30,
  },
  {
    id: '2',
    departmentName: 'Infrastructure',
    headOfDepartment: {
      name: 'Pooja Sharma',
      email: 'pooja.sharma@company.com',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sharma',
    },
    phone: '(123)456-7890',
    email: 'sanjay.ch@company.com',
    employeeCapacity: 300,
    establishedYear: 2010,
    totalEmployees: 25,
  },
  {
    id: '3',
    departmentName: 'R&D',
    headOfDepartment: {
      name: 'Sarah Smith',
      email: 'sarah.smith@company.com',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    },
    phone: '(123)456-7890',
    email: 'sarah.smi@company.com',
    employeeCapacity: 100,
    establishedYear: 2018,
    totalEmployees: 15,
  },
  {
    id: '4',
    departmentName: 'Software Dev',
    headOfDepartment: {
      name: 'Ashton Cox',
      email: 'ashton.cox@company.com',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ashton',
    },
    phone: '(123)456-7890',
    email: 'ashton.co@company.com',
    employeeCapacity: 300,
    establishedYear: 2012,
    totalEmployees: 20,
  },
  {
    id: '5',
    departmentName: 'Data Science',
    headOfDepartment: {
      name: 'Rajesh Mahajan',
      email: 'rajesh.mahajan@company.com',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh',
    },
    phone: '(123)456-7890',
    email: 'rajesh.ma@company.com',
    employeeCapacity: 250,
    establishedYear: 2015,
    totalEmployees: 18,
  },
  {
    id: '6',
    departmentName: 'Cyber Security',
    headOfDepartment: {
      name: 'Sanjana Patel',
      email: 'sanjana.patel@company.com',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sanjana',
    },
    phone: '(123)456-7890',
    email: 'sanjana.p@company.com',
    employeeCapacity: 200,
    establishedYear: 2013,
    totalEmployees: 25,
  },
  {
    id: '7',
    departmentName: 'Client Support',
    headOfDepartment: {
      name: 'Airi Satou',
      email: 'airi.satou@company.com',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Airi',
    },
    phone: '(123)456-7890',
    email: 'airi.satou@company.com',
    employeeCapacity: 125,
    establishedYear: 2011,
    totalEmployees: 10,
  },
  {
    id: '8',
    departmentName: 'IT Support',
    headOfDepartment: {
      name: 'Pooja Sarm',
      email: 'pooja.sarm2@company.com',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pooja2',
    },
    phone: '(123)456-7890',
    email: 'pooja.sarm@company.com',
    employeeCapacity: 130,
    establishedYear: 2009,
    totalEmployees: 20,
  },
  {
    id: '9',
    departmentName: 'Quality Assurance',
    headOfDepartment: {
      name: 'Sarah Smith',
      email: 'sarah.smith2@company.com',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah2',
    },
    phone: '(123)456-7890',
    email: 'sarah.smi@company.com',
    employeeCapacity: 100,
    establishedYear: 2014,
    totalEmployees: 15,
  },
  {
    id: '10',
    departmentName: 'Marketing',
    headOfDepartment: {
      name: 'Rajesh Mahajan',
      email: 'rajesh.mahajan2@company.com',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh2',
    },
    phone: '(123)456-7890',
    email: 'rajesh.ma@company.com',
    employeeCapacity: 125,
    establishedYear: 2016,
    totalEmployees: 12,
  },
  {
    id: '11',
    departmentName: 'Human Resources',
    headOfDepartment: {
      name: 'Emily Johnson',
      email: 'emily.johnson@company.com',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    },
    phone: '(123)456-7890',
    email: 'emily.johnson@company.com',
    employeeCapacity: 50,
    establishedYear: 2008,
    totalEmployees: 8,
  },
  {
    id: '12',
    departmentName: 'Finance',
    headOfDepartment: {
      name: 'Michael Chen',
      email: 'michael.chen@company.com',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    },
    phone: '(123)456-7890',
    email: 'michael.chen@company.com',
    employeeCapacity: 75,
    establishedYear: 2007,
    totalEmployees: 12,
  },
]